### ISSUE TITLE
Crash when home screen is displayed related to PagingSource

### ISSUE THREAD

**Issue by donenoyes** [indritbashkimi/TelegramExample#3]
When app is launched after logged in, the chats are shown for split second and app crashes. Seems like a Paging bug.

```
2021-02-23 17:18:37.138 7836-7836/com.ibashkimi.telegram E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ibashkimi.telegram, PID: 7836
    java.lang.IllegalStateException: The same value, 6844799889696620544, was passed as the nextKey in two
     sequential Pages loaded from a PagingSource. Re-using load keys in
     PagingSource is often an error, and must be explicitly enabled by
     overriding PagingSource.keyReuseSupported.
        at androidx.paging.PageFetcherSnapshot.doLoad(PageFetcherSnapshot.kt:413)
        at androidx.paging.PageFetcherSnapshot$doLoad$1.invokeSuspend(Unknown Source:12)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
        at androidx.compose.ui.platform.AndroidUiDispatcher.performTrampolineDispatch(AndroidUiDispatcher.kt:84)
        at androidx.compose.ui.platform.AndroidUiDispatcher.access$performTrampolineDispatch(AndroidUiDispatcher.kt:43)
        at androidx.compose.ui.platform.AndroidUiDispatcher$dispatchCallback$1.run(AndroidUiDispatcher.kt:60)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
````

**Comment by maxfalc** [comment]
Try with: override val keyReuseSupported: Boolean = true in ChatsPagingSource.kt
